ci: Add a new CI job to test against the latest Docker CLI * Add a new CI job to test against the latest Docker CLI * Update the dependabot configuration to remove the magefiles directory from the gomod package-ecosystem * Update the dependabot configuration to remove the .github/actions/* directory from the github-actions package-ecosystem * Update the go.mod and go.sum files to include new dependencies required for the new CI job * Remove the go.work and go.work.sum files as they are no longer needed * Rename the magefiles/magefile.go file to magefile.go and remove the magefiles directory

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,3 +12,51 @@ jobs:
     name: "Unit Test"
     uses: na4ma4/actions/.github/workflows/unit-test.yml@main
     secrets: inherit
+
+  latest-test:
+    needs: unit-test
+    name: "Test Against Latest Docker CLI"
+    runs-on: ubuntu-latest
+    steps: 
+    - name: Checkout
+      uses: actions/checkout@v7
+
+    - name: Update Docker CLI
+      run: |
+        mkdir -p artifacts/logs
+        curl -fsSL https://get.docker.com | sh
+        docker --version | tee artifacts/logs/docker-version.log
+
+    - name: Set up Go
+      if: ${{ hashFiles('go.mod') != '' }}
+      uses: actions/setup-go@v6
+      with:
+        go-version-file: 'go.mod'
+        cache: true
+      id: go
+
+    - name: Run Mage Build
+      uses: magefile/mage-action@v4
+      with:
+        version: latest
+        args: build:debug
+
+    - name: Test against latest docker cli
+      run: |
+        PATH="${PATH}:$(pwd)/artifacts/build/debug/$(go env GOOS)/$(go env GOARCH)"
+        docker pull ubuntu:jammy | docker-pull-output 2>&1 | tee artifacts/logs/output.log
+
+    - name: Check Test Output
+      run: |
+        EXITCODE=0
+        if grep -v " level=info " artifacts/logs/output.log; then 
+          echo "error: test output contains non-INFO lines. See artifacts/logs/output.log for details."
+          EXITCODE=1
+        fi
+        exit ${EXITCODE}
+    - name: Upload Test Output
+      if: always()
+      uses: actions/upload-artifact@v7
+      with:
+        name: docker-pull-output
+        path: artifacts/logs/*
